blank_issues_enabled: false
contact_links:
  - name: Документация по процессу
    url: https://github.com/jicool91/geoBot/tree/main/docs
    about: Ознакомьтесь с правилами перед созданием новой задачи.
